# Set update schecdule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # check for updates to GitHub actions every weekday
      interval: "daily"
