" ==================== Plugins ====================

call plug#begin("~/.config/nvim/plugged")

" Colors
Plug 'dracula/vim', {'as': 'dracula'}

Plug 'preservim/nerdtree'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'

call plug#end()

" disable compatibility with vi
set nocompatible
filetype off
filetype plugin indent on

set ttyfast

" file encoding
set encoding=utf-8
set termencoding=utf-8

" reload files changed on disk
set autoread
" write old file when switching between files
set autowrite
" no backup files
set nobackup
" no swap files
set noswapfile
" no undo files
set noundofile

" enable syntax highlighting
syntax on
" enable autoident
set autoindent
" allow backspace in insert mode
set backspace=indent,eol,start
" highlight current line
set cursorline
" enable line numbers
set number
" show the cursor position
set ruler
" show the command
set showcmd
" show the current mode
set showmode
" enable tabstop
set tabstop=2
" show the filename in the window titlebar
set title

" color
syntax enable
colorscheme dracula

:let mapleader = "-"

" ==================== Fugitive ====================

nnoremap <leader>gs :Gstatus<CR>

" ==================== NERDTree ====================

" open a NERDTree automatically when vim starts up
autocmd vimenter * NERDTree
" open a NERDTree automatically when vim starts up if no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" open NERDTree automatically when vim starts up on opening a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif

let NERDTreeShowHidden=1

" for toggling
noremap <Leader>n :NERDTreeToggle<cr>
noremap <Leader>f :NERDTreeFind<cr>
