# ~/.config/zsh/.zshrc

#
# sourced in interactive shells
#

# uncomment this and the last line for zprof info
#zmodload zsh/zprof

# Contains sensitive data which are not pushed to GitHub.
[ -r $ZDOTDIR/.zshrc.local ] && source $ZDOTDIR/.zshrc.local

#
# Aliases
#

# cd shorthand
alias ..='cd ..'

# clear screen
alias cls='clear'

# disk free, in gigabytes
alias df='df -h'
# calculates total disk usage for a folder
 alias du='du -h -c'

# print the directory structure from the current directory in tree format
alias dirtree="find . -type d|sed -e 's/[^-][^\/]*\//  |/g' -e 's/|\([^ ]\)/|-\1/'"

# enable colors in grep
alias grep='grep --color=auto'

# make some desctructive commands more interactive
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

case $(uname) in
  Darwin)
    alias ll='ls -alGpF'
    alias ls='ls -GpF'
  ;;
  *)
    alias ll='ls -al'
    alias ls='ls --color=auto'
  ;;
esac

# get week number
alias week='date +%V'

# httpie
alias https='http --default-scheme=https'

#
# Exports
#

export DOTFILES="${DOTFILES:-$HOME/.dotfiles}"

# ensure path arrays do not contain duplicates.
typeset -gU path

# set the list of directories that zsh searches for programs
path=(
  /usr/local/bin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
  /usr/local/sbin
  /usr/local/opt/make/libexec/gnubin
  $DOTFILES/bin
  $XDG_DATA_HOME/npm/bin
  $path
)

# export to sub-processes (make it inherited by child processes)
export path

export EDITOR="vim"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# support colors in less
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

#
# History
#

# command history configuration
HISTFILE=$ZDOTDIR/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
# ignore duplication command history list
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
# share command history data
setopt share_history

#
# Prompt
#

# init starship cross-shell prompt
eval "$(starship init zsh)"

# golang
export GOPATH=$HOME/Projects/go
export PATH=$GOPATH/bin:$PATH

#
# Autocompletion
#

# enable completion
autoload -Uz compinit
compinit

autoload bashcompinit
bashcompinit

zmodload -i zsh/complist

#
# Key Bindings
#

# use emacs-like key bindings by default:
bindkey -e

source .secret

#
# Plugins
#

source $ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

#zprof
